plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 6
